apiVersion: v1
kind: Namespace
metadata:
  name: carrillo-prod
  labels:
    name: carrillo-prod
    environment: production
    project: carrillo-legal-tech
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-resource-quota
  namespace: carrillo-prod
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "20"
    limits.memory: 20Gi
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limit-range
  namespace: carrillo-prod
spec:
  limits:
  - max:
      cpu: "4"
      memory: 4Gi
    min:
      cpu: "200m"
      memory: 256Mi
    default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: "500m"
      memory: 512Mi
    type: Container