apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: carrillo-dev
  labels:
    app: api-gateway
    project: carrillo-legal-tech
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-gateway-role
  namespace: carrillo-dev
  labels:
    app: api-gateway
    project: carrillo-legal-tech
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-rolebinding
  namespace: carrillo-dev
  labels:
    app: api-gateway
    project: carrillo-legal-tech
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-gateway-role
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  namespace: carrillo-dev