package com.carrilloabogados.legalcase.domain;

/**
 * Enumeration representing different types of legal documents
 */
public enum DocumentType {
    /**
     * Initial case documents provided by client
     */
    INITIAL_DOCUMENTS("Documentos Iniciales", "Documentos proporcionados inicialmente por el cliente"),
    
    /**
     * Legal contracts
     */
    CONTRACT("Contrato", "Contratos y acuerdos legales"),
    
    /**
     * Court petitions and motions
     */
    PETITION("Petición", "Demandas, peticiones y mociones judiciales"),
    
    /**
     * Court responses and answers
     */
    RESPONSE("Respuesta", "Contestaciones y respuestas judiciales"),
    
    /**
     * Evidence documents
     */
    EVIDENCE("Evidencia", "Documentos de evidencia y pruebas"),
    
    /**
     * Witness statements and depositions
     */
    WITNESS_STATEMENT("Declaración Testigo", "Declaraciones de testigos"),
    
    /**
     * Expert reports
     */
    EXPERT_REPORT("Informe Pericial", "Informes de peritos y expertos"),
    
    /**
     * Court orders and rulings
     */
    COURT_ORDER("Orden Judicial", "Órdenes y providencias del juzgado"),
    
    /**
     * Judgments and final decisions
     */
    JUDGMENT("Sentencia", "Sentencias y decisiones finales"),
    
    /**
     * Settlement agreements
     */
    SETTLEMENT("Acuerdo", "Acuerdos de conciliación"),
    
    /**
     * Appeals documents
     */
    APPEAL("Apelación", "Documentos de recursos y apelaciones"),
    
    /**
     * Power of attorney
     */
    POWER_OF_ATTORNEY("Poder", "Poderes y autorizaciones"),
    
    /**
     * Affidavits
     */
    AFFIDAVIT("Declaración Jurada", "Declaraciones juradas y afidávits"),
    
    /**
     * Correspondence with opposing party
     */
    CORRESPONDENCE("Correspondencia", "Comunicaciones con contrapartes"),
    
    /**
     * Internal memos and notes
     */
    INTERNAL_MEMO("Memo Interno", "Memorandos y notas internas"),
    
    /**
     * Financial documents
     */
    FINANCIAL("Financiero", "Documentos financieros y contables"),
    
    /**
     * Property documents
     */
    PROPERTY("Inmueble", "Documentos de bienes inmuebles"),
    
    /**
     * Corporate documents
     */
    CORPORATE("Societario", "Documentos societarios y empresariales"),
    
    /**
     * Tax documents
     */
    TAX("Tributario", "Documentos fiscales y tributarios"),
    
    /**
     * Immigration documents
     */
    IMMIGRATION("Migración", "Documentos migratorios"),
    
    /**
     * Family law documents
     */
    FAMILY("Familia", "Documentos de derecho de familia"),
    
    /**
     * Criminal law documents
     */
    CRIMINAL("Penal", "Documentos de derecho penal"),
    
    /**
     * Labor law documents
     */
    LABOR("Laboral", "Documentos de derecho laboral"),
    
    /**
     * Administrative documents
     */
    ADMINISTRATIVE("Administrativo", "Documentos administrativos"),
    
    /**
     * Other miscellaneous documents
     */
    OTHER("Otro", "Otros documentos no categorizados");
    
    private final String displayName;
    private final String description;
    
    DocumentType(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }
    
    public String getDisplayName() {
        return displayName;
    }
    
    public String getDescription() {
        return description;
    }
    
    /**
     * Check if this document type requires notarization by default
     */
    public boolean requiresNotarization() {
        return switch (this) {
            case POWER_OF_ATTORNEY, AFFIDAVIT, CONTRACT -> true;
            default -> false;
        };
    }
    
    /**
     * Check if this document type is typically confidential
     */
    public boolean isTypicallyConfidential() {
        return switch (this) {
            case INTERNAL_MEMO, WITNESS_STATEMENT, FINANCIAL, 
                 CORRESPONDENCE, EVIDENCE -> true;
            default -> false;
        };
    }
    
    /**
     * Check if this document type is generated by the law firm
     */
    public boolean isGeneratedByFirm() {
        return switch (this) {
            case PETITION, RESPONSE, INTERNAL_MEMO, CORRESPONDENCE -> true;
            default -> false;
        };
    }
}