// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quedfsyazckxktatzoen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1ZWRmc3lhemNreGt0YXR6b2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjI1NjAsImV4cCI6MjA3MTc5ODU2MH0.UJWkNI3f8qGJYTv_XtfUW2wc9o-htA_tjUje2nWH5uM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});